version: '3.8'

services:
  chrome:
    image: selenium/node-chrome:4.6.0-20221104
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_START_XVFB=false
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'


  selenium-hub:
    image: selenium/hub:4.6.0-20221104
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
